# -- https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values
global:
  {}
  # -- Pull secrets to use, if chart's `imagePullSecrets` not set.
  # imagePullSecrets:

# -- https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies
# tags:

# -- https://helm.sh/docs/topics/charts/#using-the-exports-format
# exports:

# -- Override common name.
# nameOverride:

# -- Override fully qualified name.
# fullnameOverride:

# -- Common options to apply all resources.
common:
  {}
  # -- Common labels for all resources.
  # labels:

  # -- Common annotations for all resources, except resources has its own annotations config.
  # annotations:

# -- Application service account to use.
serviceAccount:
  # -- Whether create service account or not.
  create: true

  # -- Name of service account to use or create.
  # name:

  # -- Annotations to set to service account if creating.
  # annotations:

# -- Image pull secrets.
imagePullSecrets: []

# -- Overall application configurations.
app:
  # -- Application image.
  image:
    # -- Image repository to use.
    repository: registry.gitlab.com/kkowa/apps/web

    # -- Image tag to use; defaults to chart app version.
    # tag:

    # -- Image pull policy.
    pullPolicy: Always

  # -- Application configs.
  config:
    {}
    # -- Application server URL. Will be rendered if template.
    # serverURL:

  # -- Components in application.
  components:
    # -- Main web component.
    web:
      # -- Replica count to create.
      replicas: 1

      # -- Whether automount service acount token. Defaults to false.
      # automountServiceAccountToken:

      # -- Pod security context.
      #    https://kubernetes.io/docs/concepts/security/pod-security-standards/
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      # -- Common container options.
      container:
        # -- Container security context.
        #    https://kubernetes.io/docs/concepts/security/pod-security-standards/
        securityContext:
          capabilities:
            drop:
              - ALL

          runAsUser: 10000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

        # -- Container resource quota.
        #    https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 384Mi

      # -- Auto scaling (HPA) options.
      #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/
      autoscaling:
        # -- Whether enable auto scaling or not. Disabled by default.
        enabled: false

        # -- Minimum of replicas.
        # min: 1

        # -- Maximum of replicas.
        # max: 3

        # -- Metrics used to calculate desired replica count.
        #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec
        # metrics:
        #   - type: Resource
        #     resource:
        #       name: cpu
        #       target:
        #         type: Utilization
        #         averageUtilization: 80

        # -- Detailed behavior of autoscaling.
        #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec
        # behavior:

        # -- Current status of auto scaler.
        #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerStatus
        # status:

# -- Application service to expose.
service:
  # -- Service type.
  type: ClusterIP

  # -- Service port.
  port: 3000
