apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}

  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  NODE_ENV: production

  {{- with .Values.app.config.serverURL }}
  SERVER_URL: {{ tpl . $ }}
  {{- end }}
