{{- with .Values.app.components.web }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace | quote }}
  name: {{ include "app.components.web.fullname" $ }}
  labels:
    {{- include "app.components.web.labels" $ | nindent 4 }}

  {{- with $.Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "app.components.web.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.components.web.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ include "common.serviceAccount.name" $ }}
      automountServiceAccountToken: {{ default false .automountServiceAccountToken }}
      {{- with (default $.Values.global.imagePullSecrets $.Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "app.image" $ }}
          imagePullPolicy: {{ $.Values.app.image.pullPolicy }}
          {{- with .container.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" $ }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              port: http
              path: /
          {{- with .container.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmpfs
          emptyDir: {}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
